/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package tfcode_parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int RESHAPE = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;
  /** RegularExpression Id. */
  int CONV = 8;
  /** RegularExpression Id. */
  int ADD = 9;
  /** RegularExpression Id. */
  int RELU = 10;
  /** RegularExpression Id. */
  int MAX_POOL = 11;
  /** RegularExpression Id. */
  int GRAPH = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int REAL_NUMBER = 15;
  /** RegularExpression Id. */
  int ALPHABET = 16;
  /** RegularExpression Id. */
  int LETTER = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"=\"",
    "\"reshape\"",
    "\"variable\"",
    "\"conv\"",
    "\"add\"",
    "\"relu\"",
    "\"max_pool\"",
    "\"graph\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<REAL_NUMBER>",
    "<ALPHABET>",
    "<LETTER>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\"inputs\"",
    "\")\"",
    "\"-\"",
    "\" >\"",
    "\"outputs\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
  };

}
